-- CreateTable
CREATE TABLE "FoodPlace" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "subtitle" TEXT,
    "mainColor" TEXT,
    "imageUrl" TEXT,
    "backImageUrl" TEXT,
    "campaignUrl" TEXT,
    "badge" TEXT,
    "rating" DOUBLE PRECISION,
    "storyTitle" TEXT,
    "story" TEXT,
    "phone" TEXT,
    "hoursMon" TEXT,
    "hoursTue" TEXT,
    "hoursWed" TEXT,
    "hoursThu" TEXT,
    "hoursFri" TEXT,
    "hoursSat" TEXT,
    "hoursSun" TEXT,
    "menuItem1" TEXT,
    "menuDesc1" TEXT,
    "menuPrice1" TEXT,
    "menuItem2" TEXT,
    "menuDesc2" TEXT,
    "menuPrice2" TEXT,
    "menuItem3" TEXT,
    "menuDesc3" TEXT,
    "menuPrice3" TEXT,
    "menuItem4" TEXT,
    "menuDesc4" TEXT,
    "menuPrice4" TEXT,
    "menuItem5" TEXT,
    "menuDesc5" TEXT,
    "menuPrice5" TEXT,
    "menuItem6" TEXT,
    "menuDesc6" TEXT,
    "menuPrice6" TEXT,
    "menuItem7" TEXT,
    "menuDesc7" TEXT,
    "menuPrice7" TEXT,
    "menuItem8" TEXT,
    "menuDesc8" TEXT,
    "menuPrice8" TEXT,
    "menuItem9" TEXT,
    "menuDesc9" TEXT,
    "menuPrice9" TEXT,
    "menuItem10" TEXT,
    "menuDesc10" TEXT,
    "menuPrice10" TEXT,
    "features" TEXT,
    "address" TEXT,
    "website" TEXT,
    "field1" TEXT,
    "field2" TEXT,
    "field3" TEXT,
    "field4" TEXT,
    "field5" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "subCategoryId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FoodPlace_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "FoodPlace" ADD CONSTRAINT "FoodPlace_subCategoryId_fkey" FOREIGN KEY ("subCategoryId") REFERENCES "SubCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
